// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TranslationTransformationsAnalysis.Repository;

namespace TranslationTransformationsAnalysis.Migrations
{
    [DbContext(typeof(TransformationUnitContext))]
    partial class TransformationUnitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TranslationTransformationsAnalysis.Models.ContextType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FonLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LekLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MorfLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyntLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ContextTypes");
                });

            modelBuilder.Entity("TranslationTransformationsAnalysis.Models.FormalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FonLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LekLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MorfLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlovLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyntLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FormalTypes");
                });

            modelBuilder.Entity("TranslationTransformationsAnalysis.Models.PragmalType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AxTransformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FraTtransformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KoncTransformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MegTransformation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PragmalTypes");
                });

            modelBuilder.Entity("TranslationTransformationsAnalysis.Models.TransformationUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContextFonLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContextLekLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContextMorfLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContextSyntLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormalFonLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormalLekLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormalMorfLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormalSlovLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormalSyntLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Original")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PragmalAxTransformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PragmalKoncTransformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PragmalMegTransformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PragmalPragmalFraTtransformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransformationUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
